services:
  mongo:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
  
  user-service:
    build:
      context: .
      dockerfile: ./user-service/dockerfile
    container_name: user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  task-service:
    build:
      context: .
      dockerfile: ./task-service/dockerfile
    container_name: task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
  
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "3003:3003"
    depends_on:
      - mongo
      - rabbitmq


volumes:
  mongo-data: